12:55:29 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
12:55:29 PM: INFO [customLogs.py:19] ('Fin',)
01:00:55 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:00:55 PM: INFO [customLogs.py:19] ('Fin',)
01:00:55 PM: DEBUG [customLogs.py:15] ()
01:00:55 PM: INFO [customLogs.py:19] ('Fin',)
01:02:33 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:02:33 PM: INFO [customLogs.py:19] ('Fin',)
01:02:33 PM: DEBUG [customLogs.py:15] ()
01:02:33 PM: INFO [customLogs.py:19] ('Fin',)
01:02:45 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:02:45 PM: INFO [customLogs.py:19] ('Fin',)
01:02:45 PM: DEBUG [customLogs.py:15] ()
01:02:45 PM: INFO [customLogs.py:19] ('Fin',)
01:02:58 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:02:58 PM: INFO [customLogs.py:19] ('Fin',)
01:02:58 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%s' at line 1"))
01:02:58 PM: INFO [customLogs.py:19] ('Fin',)
01:03:53 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:03:53 PM: INFO [customLogs.py:19] ('Fin',)
01:03:53 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:03:53 PM: INFO [customLogs.py:19] ('Fin',)
01:04:04 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:04:04 PM: INFO [customLogs.py:19] ('Fin',)
01:04:04 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:04:04 PM: INFO [customLogs.py:19] ('Fin',)
01:04:16 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:04:16 PM: INFO [customLogs.py:19] ('Fin',)
01:04:16 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:04:16 PM: INFO [customLogs.py:19] ('Fin',)
01:04:59 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:04:59 PM: INFO [customLogs.py:19] ('Fin',)
01:04:59 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIKEgmail.com' at line 1"))
01:04:59 PM: INFO [customLogs.py:19] ('Fin',)
01:05:13 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:05:13 PM: INFO [customLogs.py:19] ('Fin',)
01:05:13 PM: ERROR [customLogs.py:27] ('Error', OperationalError(1054, "Unknown column 'gmail.com' in 'where clause'"))
01:05:13 PM: INFO [customLogs.py:19] ('Fin',)
01:06:05 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:06:05 PM: INFO [customLogs.py:19] ('Fin',)
01:06:05 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:06:05 PM: INFO [customLogs.py:19] ('Fin',)
01:07:37 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:07:37 PM: INFO [customLogs.py:19] ('Fin',)
01:07:37 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:07:37 PM: INFO [customLogs.py:19] ('Fin',)
01:08:03 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:08:03 PM: INFO [customLogs.py:19] ('Fin',)
01:08:03 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:08:03 PM: INFO [customLogs.py:19] ('Fin',)
01:08:45 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:08:45 PM: INFO [customLogs.py:19] ('Fin',)
01:08:45 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:08:45 PM: INFO [customLogs.py:19] ('Fin',)
01:09:19 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:09:19 PM: INFO [customLogs.py:19] ('Fin',)
01:09:19 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:09:19 PM: INFO [customLogs.py:19] ('Fin',)
01:14:00 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:14:00 PM: INFO [customLogs.py:19] ('Fin',)
01:14:00 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:14:00 PM: INFO [customLogs.py:19] ('Fin',)
01:16:27 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:16:27 PM: INFO [customLogs.py:19] ('Fin',)
01:16:27 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:16:27 PM: INFO [customLogs.py:19] ('Fin',)
01:17:11 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:17:11 PM: INFO [customLogs.py:19] ('Fin',)
01:17:11 PM: DEBUG [customLogs.py:15] ()
01:17:11 PM: INFO [customLogs.py:19] ('Fin',)
01:17:32 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:17:32 PM: INFO [customLogs.py:19] ('Fin',)
01:17:32 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:17:32 PM: INFO [customLogs.py:19] ('Fin',)
01:17:52 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:17:52 PM: INFO [customLogs.py:19] ('Fin',)
01:17:52 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:17:52 PM: INFO [customLogs.py:19] ('Fin',)
01:18:03 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:18:03 PM: INFO [customLogs.py:19] ('Fin',)
01:18:03 PM: ERROR [customLogs.py:27] ('Error', ProgrammingError('not all arguments converted during bytes formatting'))
01:18:03 PM: INFO [customLogs.py:19] ('Fin',)
01:18:11 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:18:11 PM: INFO [customLogs.py:19] ('Fin',)
01:18:11 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:18:11 PM: INFO [customLogs.py:19] ('Fin',)
01:44:13 PM: DEBUG [customLogs.py:15] (('juan',), ('paco',), ('laura',))
01:44:13 PM: INFO [customLogs.py:19] ('Fin',)
01:44:13 PM: DEBUG [customLogs.py:15] ((1, 'juan', 'hern', 'juanh@gmail.com'), (3, 'laura', 'fern', 'laufer@gmail.com'))
01:44:13 PM: INFO [customLogs.py:19] ('Fin',)
01:44:13 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:44:21 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:45:05 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:46:35 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:47:35 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not all arguments converted during bytes formatting',)
01:47:59 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:48:31 PM: ERROR [customLogs.py:27] ('Ocurrió un error: float argument required, not bytes',)
01:48:45 PM: ERROR [customLogs.py:27] ('Ocurrió un error: not enough arguments for format string',)
01:50:24 PM: DEBUG [customLogs.py:15] Registros Actualizados: 1
01:50:55 PM: DEBUG [customLogs.py:15] Registros Actualizados: 0
01:51:33 PM: DEBUG [customLogs.py:15] Registros Actualizados: 0
01:51:57 PM: DEBUG [customLogs.py:15] Registros Actualizados: 1
01:52:31 PM: DEBUG [customLogs.py:15] Registros Actualizados: 0
01:53:00 PM: DEBUG [customLogs.py:15] Registros Actualizados: 1
10:18:07 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:18:07 AM: INFO [customLogs.py:19] ('Conexion cerrada',)
10:18:48 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:18:48 AM: INFO [customLogs.py:19] ('Conexion cerrada',)
10:19:30 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:19:30 AM: INFO [customLogs.py:19] ('Conexion cerrada',)
10:21:53 AM: INFO [customLogs.py:19] ('Fin',)
10:22:44 AM: INFO [customLogs.py:19] ('Fin',)
10:24:18 AM: INFO [customLogs.py:19] ('Fin',)
10:25:34 AM: INFO [customLogs.py:19] ('Fin',)
10:26:14 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:27:20 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:27:20 AM: ERROR [customLogs.py:27] ('Error', TypeError('__str__ returned non-string (type tuple)'))
10:27:37 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:28:17 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:29:50 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:30:19 AM: INFO [customLogs.py:19] ('Conexion abierta',)
10:30:43 AM: INFO [customLogs.py:19] ('Conexion abierta',)
